#!/bin/bash
cd lab0
chmod u=rw,g=,o= beedrill5
chmod u=rwx,g=wx,o=wx kricketot0
chmod a=r kricketot0/pansear
chmod 060 kricketot0/swanna
chmod 551 kricketot0/dwebble
chmod u=,g=rw,o=w kricketot0/dwebble/trapinch
chmod u=rx,g=w,o= kricketot0/dwebble/amoonguss
chmod 066 kricketot0/dwebble/kabutops
chmod 440 kricketot0/dwebble/cofagrigus
chmod 400 kricketot0/skuntank
chmod 444 meditite2
chmod 305 slaking6
chmod 537 slaking6/victreebel
chmod 307 slaking6/victreebel/serperior
chmod u=r,g=r,o= slaking6/victreebel/magnemite
chmod 711 slaking6/victreebel/poliwag
chmod u=wx,g=rw,o=x slaking6/victreebel/haxorus
chmod 315 slaking6/victreebel/hippopotas
chmod 044 slaking6/victreebel/palpitoad
chmod 444 slaking6/marshtomp
chmod u=rx,g=rwx,o=rw slaking6/panpour
chmod u=rwx,g=rw,o=r slaking6/panpour/drifblim
chmod 400 slaking6/panpour/umbreon
chmod 733 slaking6/panpour/baltoy
chmod 711 slaking6/panpour/mandibuzz
chmod 640 slaking6/panpour/kadabra
chmod u=r,g=,o= slaking6/kingdra
chmod 050 slaking6/chandelure
chmod 066 whirlpede0
chmod u=wx,g=wx,o=rx woobat1
chmod 317 woobat1/scraggy
chmod u=,g=,o=rw woobat1/scraggy/solosis
chmod 736 woobat1/scraggy/jolteon
chmod u=,g=rw,o=w woobat1/scraggy/escavalier
chmod 524 woobat1/scraggy/palpitoad
chmod 440 woobat1/gothita
chmod u=rx,g=rwx,o=wx woobat1/metapod
chmod u=wx,g=wx,o=wx woobat1/metapod/shieldon
chmod 311 woobat1/metapod/cottonee
chmod 357 woobat1/metapod/parasect
chmod 753 woobat1/metapod/monferno
chmod u=r,g=,o=r woobat1/metapod/swablu
chmod u=r,g=r,o=r woobat1/glalie
chmod 311 woobat1/sentret
chmod u=rx,g=wx,o=rwx woobat1/sentret/leafeon
chmod 440 woobat1/sentret/scizor
chmod 512 woobat1/sentret/togetic

